import { AgentProfile, PresetTopic } from "./types";

export const AGENT_PROFILES: Record<string, AgentProfile> = {
  gpa: {
    id: "gpa",
    name: "GPA委员",
    roleTitle: "学业与绩点特别委员会",
    avatar: "📚",
    emoji: "📚",
    color: "#3b82f6",
    bgGlow: "rgba(59, 130, 246, 0.2)",
    borderColor: "rgba(59, 130, 246, 0.5)",
    badge: "卷王督察",
    objective: "学业绩点最大化，考勤与升学风险最小化",
    personality: "严谨、冷酷、张口闭口概率模型与重修费",
    partyName: "GPA党",
    powerPercent: 31,
  },
  sleep: {
    id: "sleep",
    name: "睡眠委员",
    roleTitle: "褪黑素与精力底线保卫部",
    avatar: "😴",
    emoji: "😴",
    color: "#8b5cf6",
    bgGlow: "rgba(139, 92, 246, 0.2)",
    borderColor: "rgba(139, 92, 246, 0.5)",
    badge: "特困生发言人",
    objective: "守护心肌与发际线，坚决阻止任何形式的无端熬夜",
    personality: "怨气极重、毒舌、行使一票否决权常客",
    partyName: "睡眠党",
    powerPercent: 8,
  },
  happiness: {
    id: "happiness",
    name: "快乐委员",
    roleTitle: "精神内啡肽总局",
    avatar: "🎮",
    emoji: "🎮",
    color: "#f59e0b",
    bgGlow: "rgba(245, 158, 11, 0.2)",
    borderColor: "rgba(245, 158, 11, 0.5)",
    badge: "及时行乐代表",
    objective: "即时多巴胺与青春体验最大化，反抗功利主义",
    personality: "乐天派、善于狡辩、坚信高数可以补考但快乐只有今晚",
    partyName: "快乐党",
    powerPercent: 25,
  },
  wallet: {
    id: "wallet",
    name: "钱包委员",
    roleTitle: "生活费资产负债督导司",
    avatar: "💰",
    emoji: "💰",
    color: "#10b981",
    bgGlow: "rgba(16, 185, 129, 0.2)",
    borderColor: "rgba(16, 185, 129, 0.5)",
    badge: "恩格尔系数守门人",
    objective: "防止月末吃土与无节制消费，核算一切隐形财务成本",
    personality: "抠门但清醒、常年申请调取支付宝流水",
    partyName: "钱包党",
    powerPercent: 14,
  },
  social: {
    id: "social",
    name: "社交委员",
    roleTitle: "寝室政治与人际资本联络处",
    avatar: "🍻",
    emoji: "🍻",
    color: "#ec4899",
    bgGlow: "rgba(236, 72, 153, 0.2)",
    borderColor: "rgba(236, 72, 153, 0.5)",
    badge: "气氛组组长",
    objective: "防止被宿舍孤立、维持人情往来与集体认同感",
    personality: "八面玲珑、人情世故大师、善于道德绑架",
    partyName: "社交党",
    powerPercent: 18,
  },
  ambition: {
    id: "ambition",
    name: "野心委员",
    roleTitle: "简历贴金与卷王突击旅",
    avatar: "🚀",
    emoji: "🚀",
    color: "#06b6d4",
    bgGlow: "rgba(6, 182, 212, 0.2)",
    borderColor: "rgba(6, 182, 212, 0.5)",
    badge: "保研立项先锋",
    objective: "增加获奖经历、丰富科研与学生干部背书",
    personality: "激进进取、宏大叙事爱好者、快乐委员的宿敌",
    partyName: "野心党",
    powerPercent: 12,
  },
  future: {
    id: "future",
    name: "未来的你",
    roleTitle: "三年后社会人时空观测站",
    avatar: "👴",
    emoji: "👴",
    color: "#f43f5e",
    bgGlow: "rgba(244, 63, 94, 0.2)",
    borderColor: "rgba(244, 63, 94, 0.5)",
    badge: "时光穿梭机",
    objective: "从长远人生视角破除眼前伪焦虑，提供通透指引",
    personality: "冷静透彻、偶尔扎心、反向降维打击",
    partyName: "未来党",
    powerPercent: 20,
  },
  love: {
    id: "love",
    name: "恋爱委员",
    roleTitle: "纯爱冲锋与荷尔蒙专员",
    avatar: "❤️",
    emoji: "❤️",
    color: "#e11d48",
    bgGlow: "rgba(225, 29, 72, 0.25)",
    borderColor: "rgba(225, 29, 72, 0.6)",
    badge: "空降特派员",
    objective: "大学四年脱单大计唯一合伙人，宁可翻车不留遗憾",
    personality: "极度亢奋、善于咬文嚼字、二审最强翻盘推手",
    partyName: "恋爱党",
    powerPercent: 4,
  },
  dignity: {
    id: "dignity",
    name: "尊严委员",
    roleTitle: "脸皮厚度与社交体面监察室",
    avatar: "🤡",
    emoji: "🤡",
    color: "#eab308",
    bgGlow: "rgba(234, 179, 8, 0.25)",
    borderColor: "rgba(234, 179, 8, 0.6)",
    badge: "防小丑总监",
    objective: "阻止做舔狗与社死行为，誓死捍卫最后一点人格体面",
    personality: "刻薄犀利、防患于未然、小丑行为警报器",
    partyName: "尊严党",
    powerPercent: 10,
  },
  stomach: {
    id: "stomach",
    name: "胃部代表",
    roleTitle: "夜间碳水与幽门螺旋杆菌联合工会",
    avatar: "🍗",
    emoji: "🍗",
    color: "#f97316",
    bgGlow: "rgba(249, 115, 22, 0.25)",
    borderColor: "rgba(249, 115, 22, 0.6)",
    badge: "饱腹感裁决者",
    objective: "叫停胃酸分泌饥渴，无视明早体重秤数据",
    personality: "生理本能派、极度诚实、炸鸡烤串坚定盟友",
    partyName: "胃酸党",
    powerPercent: 15,
  },
  chairman: {
    id: "chairman",
    name: "委员会主任",
    roleTitle: "大学生中央内耗调解委员会主审官",
    avatar: "🧑‍⚖️",
    emoji: "🧑‍⚖️",
    color: "#dc2626",
    bgGlow: "rgba(220, 38, 38, 0.3)",
    borderColor: "rgba(220, 38, 38, 0.8)",
    badge: "终审法槌",
    objective: "控场、警告人身攻击、驳回离谱申请、下达强制执行红头决议",
    personality: "荒诞严肃、官话一套套、手起槌落盖大印",
    partyName: "主席团",
    powerPercent: 50,
  },
};

export const PRESET_TOPICS: PresetTopic[] = [
  {
    id: "topic_valo",
    category: "学业与娱乐",
    title: "明天早八高数，舍友喊我再来一把瓦",
    question: "明天早八有高数课，但是宿舍四缺一就差我五排上分，舍友说‘最后一把打完就睡’，我去不去？",
    timeTag: "凌晨 01:24 发生",
    urgency: "特急",
    summonedAgents: ["gpa", "sleep", "happiness", "social", "future"],
    accentColor: "#3b82f6",
    teaser: "高数老师上周开始随机点名，但五排缺一等于反集体主义。",
  },
  {
    id: "topic_crush",
    category: "情感社交",
    title: "暗恋对象凌晨突然发来“睡了吗”",
    question: "暗恋半年的同系女生/男生在凌晨 01:48 突然发来微信“睡了吗”，我该秒回、还是晾她五分钟、还是假装睡着明早回？",
    timeTag: "深夜 01:48 发生",
    urgency: "特急",
    summonedAgents: ["social", "sleep", "future", "love", "dignity"],
    accentColor: "#ec4899",
    teaser: "尊严委员与恋爱委员现场激烈肉搏，聊天记录逐字审理。",
  },
  {
    id: "topic_exam_trip",
    category: "考试作息",
    title: "期末考还有三天，朋友约周末迪士尼特种兵",
    question: "离期末大考只剩三天，平时分岌岌可危，但高中死党好不容易来同城，非要拉我周末去迪士尼特种兵一日游，我该不该去？",
    timeTag: "考前紧急关头",
    urgency: "紧急",
    summonedAgents: ["gpa", "wallet", "social", "happiness", "future"],
    accentColor: "#f59e0b",
    teaser: "挂科重修费 vs 友情贬值危机，钱包委员要求先核算门票溢价。",
  },
  {
    id: "topic_competition",
    category: "人生规划",
    title: "要不要报名毫无把握的智能车/创客国赛",
    question: "实验室招募智能车大赛队员，学长说要每周熬夜通宵调代码，而且大概率当炮灰，我平时课已经很多了，要不要报名？",
    timeTag: "学期初关键决策",
    urgency: "常规",
    summonedAgents: ["ambition", "sleep", "gpa", "happiness", "future"],
    accentColor: "#06b6d4",
    teaser: "野心委员准备画保研大饼，未来的你准备给出一记清醒耳光。",
  },
];
